/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://ting3q6rwveztbmxyhtntiat7y.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-n6gzun3anneyjofcdz6zlarxxm",
    "aws_cognito_identity_pool_id": "us-east-2:9a4cd4a2-41b5-4e38-bf25-5c60f438d7bd",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Tf0Vj2THX",
    "aws_user_pools_web_client_id": "19ukaavs9lkrv7knotv6250shm",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
